export const COMMANDS = {
  restart: "vue.restartLanguageServer",
  status: "vue.showServerStatus",
  debugInfo: "vue.copyDebugInfo",
  lspCapabilities: "vue.copyLspCapabilities",
  probe: "vue.probeLspAtCursor",
  renameSymbol: "vue.renameSymbol",
  quickFix: "vue.quickFix",
  addMissingImports: "vue.addMissingImports",
  removeUnusedImports: "vue.removeUnusedImports",
  organizeImports: "vue.organizeImports",
  redetect: "vue.redetectToolchain",
  openSettings: "vue.openSettings",
  resetGlobalSettings: "vue.resetGlobalSettings",
  resetWorkspaceSettings: "vue.resetWorkspaceSettings"
};

export const CONFIG = {
  serverEnabled: "vue.server.enabled",
  nodePath: "vue.node.path",
  serverPath: "vue.languageServer.path",
  tsdk: "vue.typescript.tsdk",
  debug: "vue.debug",
  lspLogs: "vue.lsp.logs",
  maxOldSpaceSize: "vue.maxOldSpaceSize",
  memoryAutoRetryEnabled: "vue.memory.autoRetry.enabled",
  restartOnConfigChange: "vue.server.restartOnConfigChange",
  diagnosticsEnabled: "vue.diagnostics.enabled",
  vueDiagnosticsEnabled: "vue.diagnostics.vue.enabled",
  typescriptDiagnosticsEnabled: "vue.diagnostics.typescript.enabled",
  diagnosticsOnChangeEnabled: "vue.diagnostics.onChange.enabled",
  diagnosticsOnSaveEnabled: "vue.diagnostics.onSave.enabled",
  codeActionsEnabled: "vue.codeActions.enabled",
  typescriptEnabled: "vue.typescript.enabled",
  typescriptNavigationEnabled: "vue.typescript.navigation.enabled",
  typescriptHoverEnabled: "vue.typescript.hover.enabled",
  typescriptDefinitionEnabled: "vue.typescript.definition.enabled",
  typescriptReferencesEnabled: "vue.typescript.references.enabled",
  typescriptRenameEnabled: "vue.typescript.rename.enabled",
  typescriptCodeActionsEnabled: "vue.typescript.codeActions.enabled",
  completionEnabled: "vue.completion.enabled",
  completionAutoImport: "vue.completion.autoImport",
  proxyFallbackEnabled: "vue.proxy.fallbackToVueLanguageServer.enabled",
  workspaceDiscoveryEnabled: "vue.workspace.discovery.enabled",
  workspaceWatchConfigFilesEnabled: "vue.workspace.watchConfigFiles.enabled",
  workspaceWatchPackageFilesEnabled: "vue.workspace.watchPackageFiles.enabled",
  initializationOptions: "vue.initializationOptions"
};
